### PR TITLE
chore: update node version from 16 to 20

### PR DESCRIPTION
**Pull request by Tritolium**
Nodejs 16 is EOL, 20 is the current LTS

### CODE REVIEW

**Comment by MostefaKamalLala** [comment]
You were faster then me @Tritolium 😁

**Comment by Tritolium** [comment]
@jossef could you please Review this PR?

**Comment by dylan-smith** [comment]
This causes annoying warnings in my builds. Please accept this PR.
image

**Review by jossef — APPROVED** [review]

**Comment by jossef** [comment]
Merged, sorry about the delay and thank you

**Pull request merged**
